WSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  ExampleJavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.freitag.stefan.alexa.roombooker.RoomBookerSpeechletRequestStreamHandler
      CodeUri: ./roomBooker-fat-0.0.3-SNAPSHOT.jar
      Runtime: java8
